import type {Metadata} from 'next';
import {Montserrat} from 'next/font/google';
import {auth} from '@/auth';

import './globals.scss';
import React from 'react';
import Image from 'next/image';
import {SessionProvider} from 'next-auth/react';
import {redirect} from 'next/navigation';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['700', '600', '400', '500'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body className={montserrat.className}>
          {children}
          <Image
            className="main-bg"
            src="/main-bg.svg"
            alt="Main-bg"
            width={1000}
            height={1000}
          />
        </body>
      </SessionProvider>
    </html>
  );
}
